# 文件名: .github/workflows/sync-to-hf.yml
# 最终修正版，使用了最新的、稳定的Action版本号

name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 使用最新的 checkout v4 版本

      # ⬇️⬇️⬇️ 关键的修复在这里：将 v6 换成 v0 ⬇️⬇️⬇️
      - name: Push to Hugging Face Hub
        uses: huggingface/hub-action@v0 # 使用 v0 这个长期稳定分支
        with:
          repo_id: "fenghuixianyu/MixTex_Streamlit"
          repo_type: space
          token: ${{ secrets.HF_TOKEN }}
          # ⬇️⬇️⬇️ 新增：为了兼容LFS，我们需要明确地拉取LFS文件 ⬇️⬇️⬇️
          fetch_depth: 0 # 确保拉取完整历史
          lfs: true # 确保检出LFS文件