# 文件名: .github/workflows/sync-to-hf.yml
# 严格遵循Hugging Face官方教程的最终版

name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main  # 确保这是你的主分支名
  
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # 第一步：检出完整历史的仓库，并处理LFS文件
      # 官方教程使用了 v3，为了稳定性我们保持一致
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      # 第二步：【关键】使用一个独立的Action来推送到Hub
      # 这是比我们自己写 git push 命令更稳健、更官方的做法
      - name: Push to Hugging Face Hub
        uses: huggingface/hub-action@v6
        with:
          # 你的Hugging Face用户名/Space名
          repo_id: "fenghuixianyu/MixTex_Streamlit"
          # 告诉它这是一个 Space 仓库
          repo_type: space
          # 从GitHub Secrets获取认证Token
          token: ${{ secrets.HF_TOKEN }}
          # 【关键】这个Action内部会处理好所有认证和推送的细节