# 文件名: .github/workflows/sync-to-hf.yml
# 最终修正版，解决了 "shallow update not allowed" 问题

name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # ⬇️⬇️⬇️ 关键的修复在这里 ⬇️⬇️⬇️
      - name: Checkout repository (FULL HISTORY)
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0 告诉机器人下载完整的、非浅层的历史记录
          # 这是解决 "shallow update not allowed" 问题的唯一方法
          fetch-depth: 0
          lfs: true # 我们需要让 checkout 知道这是一个 LFS 仓库

      # 第二步：将完整的历史和代码强制推送到 Hugging Face Space
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 因为 checkout 时 lfs=true，Git LFS 会自动处理大文件
          # 我们不再需要复杂的“指针推送”模式，直接进行标准推送
          git push --force https://fenghuixianyu:$HF_TOKEN@huggingface.co/spaces/fenghuixianyu/MixTex_Streamlit main

      # 第三步：(可选，但推荐保留) 重启 Space 以确保更新生效
      - name: Trigger Space restart
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          curl -X POST \
               -H "Authorization: Bearer $HF_TOKEN" \
               "https://huggingface.co/api/spaces/fenghuixianyu/MixTex_Streamlit/restart"